// <auto-generated />
namespace Bombando.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class limpando : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(limpando));
        
        string IMigrationMetadata.Id
        {
            get { return "201605230113063_limpando"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
