// <auto-generated />
namespace Bombando.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TabelaDataAtualizada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TabelaDataAtualizada));
        
        string IMigrationMetadata.Id
        {
            get { return "201605240206316_TabelaDataAtualizada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
